# Generated by Django 5.0.1 on 2024-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0003_rename_stud_city_student_stud_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Stud_Phn',
            field=models.CharField(max_length=15),
        ),
    ]
